[server]
  port = 8080

[trading]
  log_path = "./logs/trading.log"

[redis]
  addr = "redis:6379"

[market]
  intervals = ["5m", "15m"]

[chart]
  [chart.candles]
    limit = 500

[binance]
  [binance.rate_limit]
    requests = 200
    duration = "1m"

[notify]
  [notify.channels]
    "notify.channels.futures_announcement" = 1630847448
  [notify.config]
    expiration = "10m"

[telegram]
  token = "5948925858:AAFyt5WarYZZZuix7gWxkuBcUDgQYiMhtIY"
