// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package signal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignalServiceClient is the client API for SignalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalServiceClient interface {
	PerformSignalAnalysis(ctx context.Context, in *PerformSignalRequestAnalysis, opts ...grpc.CallOption) (*PerformSignalResponseAnalysis, error)
	ChangeTradingSettings(ctx context.Context, in *ChangeTradingSettingsRequest, opts ...grpc.CallOption) (*ChangeTradingSettingsResponse, error)
}

type signalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalServiceClient(cc grpc.ClientConnInterface) SignalServiceClient {
	return &signalServiceClient{cc}
}

func (c *signalServiceClient) PerformSignalAnalysis(ctx context.Context, in *PerformSignalRequestAnalysis, opts ...grpc.CallOption) (*PerformSignalResponseAnalysis, error) {
	out := new(PerformSignalResponseAnalysis)
	err := c.cc.Invoke(ctx, "/v1.signal.SignalService/PerformSignalAnalysis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalServiceClient) ChangeTradingSettings(ctx context.Context, in *ChangeTradingSettingsRequest, opts ...grpc.CallOption) (*ChangeTradingSettingsResponse, error) {
	out := new(ChangeTradingSettingsResponse)
	err := c.cc.Invoke(ctx, "/v1.signal.SignalService/ChangeTradingSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignalServiceServer is the server API for SignalService service.
// All implementations should embed UnimplementedSignalServiceServer
// for forward compatibility
type SignalServiceServer interface {
	PerformSignalAnalysis(context.Context, *PerformSignalRequestAnalysis) (*PerformSignalResponseAnalysis, error)
	ChangeTradingSettings(context.Context, *ChangeTradingSettingsRequest) (*ChangeTradingSettingsResponse, error)
}

// UnimplementedSignalServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSignalServiceServer struct {
}

func (UnimplementedSignalServiceServer) PerformSignalAnalysis(context.Context, *PerformSignalRequestAnalysis) (*PerformSignalResponseAnalysis, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerformSignalAnalysis not implemented")
}
func (UnimplementedSignalServiceServer) ChangeTradingSettings(context.Context, *ChangeTradingSettingsRequest) (*ChangeTradingSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeTradingSettings not implemented")
}

// UnsafeSignalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalServiceServer will
// result in compilation errors.
type UnsafeSignalServiceServer interface {
	mustEmbedUnimplementedSignalServiceServer()
}

func RegisterSignalServiceServer(s grpc.ServiceRegistrar, srv SignalServiceServer) {
	s.RegisterService(&SignalService_ServiceDesc, srv)
}

func _SignalService_PerformSignalAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerformSignalRequestAnalysis)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServiceServer).PerformSignalAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.signal.SignalService/PerformSignalAnalysis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServiceServer).PerformSignalAnalysis(ctx, req.(*PerformSignalRequestAnalysis))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignalService_ChangeTradingSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeTradingSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServiceServer).ChangeTradingSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.signal.SignalService/ChangeTradingSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServiceServer).ChangeTradingSettings(ctx, req.(*ChangeTradingSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignalService_ServiceDesc is the grpc.ServiceDesc for SignalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.signal.SignalService",
	HandlerType: (*SignalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PerformSignalAnalysis",
			Handler:    _SignalService_PerformSignalAnalysis_Handler,
		},
		{
			MethodName: "ChangeTradingSettings",
			Handler:    _SignalService_ChangeTradingSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/signal/service.proto",
}
